const { test, expect } = require('@playwright/test');

test('Login Modal opens and authenticates user', async ({ page }) => {
  await page.goto('file://' + __dirname + '/../index.html');

  // Listen for alert and auto-dismiss it
  page.on('dialog', async dialog => {
    await dialog.accept();
  });

  // Open the login modal
  await page.click('#loginBtn');
  await expect(page.locator('#loginForm')).toBeVisible();

  // Fill in the login form
  await page.fill('#email', 'test@email.com');
  await page.fill('#password', '1234');

  // Click the login button
  await page.click('#loginForm button');

  // ✅ Wait for modal to close
  await expect(page.locator('#authModal')).not.toBeVisible();
});
